name: Handle new mails

on:
  # GitGitGadget's GitHub App is expected to trigger this on `git-mailing-list-mirror` updates
  workflow_dispatch:
  push:
    branches:
      - migrate-gitgitgadget-to-github-actions

env:
  GITGITGADGET_DRY_RUN: 'true'

concurrency:
  group: ${{ github.workflow }}

jobs:
  handle-new-mails:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/create-github-app-token@v1
    #   id: gitgitgadget-git-token
    #   with:
    #     app-id: ${{ secrets.GITGITGADGET_GITHUB_APP_ID }}
    #     private-key: ${{ secrets.GITGITGADGET_GITHUB_APP_PRIVATE_KEY }}
    #     owner: gitgitgadget
    #     repositories: git
    # - uses: actions/create-github-app-token@v1
    #   id: git-git-token
    #   with:
    #     app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
    #     private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
    #     owner: git
    #     repositories: git
    # - uses: actions/create-github-app-token@v1
    #   id: dscho-git-token
    #   with:
    #     app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
    #     private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
    #     owner: dscho
    #     repositories: git
    - uses: dscho/gitgitgadget/handle-new-mails@v1
      with:
        pr-repo-token: intentionally left blank
        upstream-repo-token: intentionally left blank
        test-repo-token: intentionally left blank
